### ISSUE TITLE
Missing Competition Ranks

### ISSUE THREAD

**Issue by TurtIeSocks** [Pupitar/ohbemgo#4]
These results compare RDM PVP vs Ohbem GO pvp. The results with Ohbem JS are the same as RDM PVP.

Guide:
```
pokemon_id
Atk
Def
Sta
Level

pokemon_id
Rank
Cp
Level/cap
```

Spheal
363
4
14
14
1

365
3
500
7

====================

Poliwag
60
11
15
15
24

62
3
2497
39/40

====================

Pikachu - winter 2020
25
1
15
15
16

25
1
500
21

====================

Bidoof
399
0
15
14
6

400
1
499
10.5

400
2
1498
33

RDM
```json
{
    "little": [
        {
            "dense_rank": 23,
            "cap": 40,
            "rank": 32,
            "ordinal_rank": 33,
            "cp": 493,
            "form": 1667,
            "gender": 1,
            "pokemon": 399,
            "percentage": 0.982754803145974,
            "capped": true,
            "competition_rank": 32,
            "level": 28.5
        },
        {
            "cap": 40,
            "capped": true,
            "pokemon": 400,
            "percentage": 1.0,
            "cp": 499,
            "rank": 1,
            "gender": 1,
            "level": 10.5,
            "competition_rank": 1,
            "dense_rank": 1,
            "ordinal_rank": 2,
            "form": 1670
        }
    ],
    "great": [
        {
            "cp": 1498,
            "dense_rank": 2,
            "cap": 40,
            "capped": true,
            "percentage": 0.9995893471107288,
            "gender": 1,
            "ordinal_rank": 2,
            "form": 1670,
            "competition_rank": 2,
            "pokemon": 400,
            "level": 33.0,
            "rank": 2
        }
    ]
}
```
Golbat
```json
{}
```

Golbat settings:
```toml
[pvp]
enabled = true
include_hundos_under_cap = false
level_caps = [40, 50, 51]

[[pvp.leagues]]
name = "little"
cap = 500
little = false

[[pvp.leagues]]
name = "great"
cap = 1500
little = false

[[pvp.leagues]]
name = "ultra"
cap = 2500
little = false
```
RDM
```yml
      PVP_DEFAULT_RANK: competition
      PVP_LITTLE_FILTER: 500
      PVP_GREAT_FILTER: 1500
      PVP_ULTRA_FILTER: 2500
      PVP_LEVEL_CAPS: 40,50,51
```
